// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as HexToRgb$WcagColorContrast from "../../src/transformers/HexToRgb.res.mjs";

Vitest.describe("Hex to Int", () => {
  Vitest.test("ff", () => {
    let match = HexToRgb$WcagColorContrast.hexToInt("ff");
    if (match !== undefined) {
      if (match === 255) {
        return;
      }
      throw {
        RE_EXN_ID: "Failure",
        _1: "Expected ff to be 255",
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: "Failure",
      _1: "Expected ff to be 255",
      Error: new Error()
    };
  });
  Vitest.test("00", () => {
    let match = HexToRgb$WcagColorContrast.hexToInt("00");
    if (match !== undefined) {
      if (match === 0) {
        return;
      }
      throw {
        RE_EXN_ID: "Failure",
        _1: "Expected ff to be 255",
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: "Failure",
      _1: "Expected ff to be 255",
      Error: new Error()
    };
  });
});

Vitest.describe("HEX to RGB", () => {
  Vitest.test("White", () => {
    let match = HexToRgb$WcagColorContrast.hexToRgb("ffffff");
    if (match !== undefined) {
      if (match.r !== 255) {
        throw {
          RE_EXN_ID: "Failure",
          _1: "Expected #ffffff to be HEX",
          Error: new Error()
        };
      }
      if (match.g !== 255) {
        throw {
          RE_EXN_ID: "Failure",
          _1: "Expected #ffffff to be HEX",
          Error: new Error()
        };
      }
      if (match.b !== 255) {
        throw {
          RE_EXN_ID: "Failure",
          _1: "Expected #ffffff to be HEX",
          Error: new Error()
        };
      }
      if (match.a === 1.0) {
        return;
      }
      throw {
        RE_EXN_ID: "Failure",
        _1: "Expected #ffffff to be HEX",
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: "Failure",
      _1: "Expected #ffffff to be HEX",
      Error: new Error()
    };
  });
});

/*  Not a pure module */
