// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";

function expect(prim0, prim1) {
  Vitest.expect(prim0, prim1);
}

export {
  expect,
}
/* vitest Not a pure module */
