// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as WcagColorContrast$WcagColorContrast from "../src/WcagColorContrast.res.mjs";

Vitest.describe("Colour format", () => {
  Vitest.test("detect standard HEX 6 chars", () => {
    let match = WcagColorContrast$WcagColorContrast.format("#ffffff");
    if (match !== undefined) {
      if (match === "HEX") {
        return;
      }
      throw {
        RE_EXN_ID: "Failure",
        _1: "Expected #ffffff to be HEX",
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: "Failure",
      _1: "Expected #ffffff to be HEX",
      Error: new Error()
    };
  });
});

/*  Not a pure module */
