// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ColorRegex$WcagColorContrast from "./ColorRegex.res.mjs";

function getColorFormat(colorString) {
  let s = colorString.trim();
  if (ColorRegex$WcagColorContrast.hex.test(s)) {
    return "HEX";
  }
}

export {
  getColorFormat,
}
/* ColorRegex-WcagColorContrast Not a pure module */
