// Generated by ReScript, PLEASE EDIT WITH CARE


function extract(colorString, format) {
  let s = colorString.trim();
  if (format !== undefined) {
    if (format === "HEX") {
      if (!(s.length >= 4 && "#".startsWith(s))) {
        return;
      }
      let hex = s.slice(1);
      return {
        TAG: "HEX",
        _0: hex
      };
    }
    throw {
      RE_EXN_ID: "Match_failure",
      _1: [
        "ColorValues.res",
        4,
        2
      ],
      Error: new Error()
    };
  }
  throw {
    RE_EXN_ID: "Match_failure",
    _1: [
      "ColorValues.res",
      4,
      2
    ],
    Error: new Error()
  };
}

export {
  extract,
}
/* No side effect */
