// Generated by ReScript, PLEASE EDIT WITH CARE


function extract(colorString, format) {
  let s = colorString.trim();
  if (format !== undefined && format === "HEX" && s.length >= 4 && s.startsWith("#")) {
    return {
      format: "HEX",
      value: s.slice(1)
    };
  }
}

export {
  extract,
}
/* No side effect */
