// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ColorRegex from "./ColorRegex.res.mjs";

function getColorFormat(colorString) {
  let s = colorString.trim();
  if (ColorRegex.hex.test(s)) {
    return "HEX";
  }
}

export {
  getColorFormat,
}
/* ColorRegex Not a pure module */
