// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as ColorValues$WcagColorContrast from "../../src/parsers/ColorValues.res.mjs";

Vitest.describe("HEX", () => {
  Vitest.test("detect standard HEX 6 chars", () => {
    let result = ColorValues$WcagColorContrast.extract("#ffffff", "HEX");
    if (result !== undefined) {
      if (result.format === "HEX") {
        if (result.value === "ffffff") {
          return;
        }
        throw {
          RE_EXN_ID: "Failure",
          _1: "Expected Some({format: HEX, value: \"ffffff\"}",
          Error: new Error()
        };
      }
      throw {
        RE_EXN_ID: "Failure",
        _1: "Expected Some({format: HEX, value: \"ffffff\"}",
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: "Failure",
      _1: "Expected Some({format: HEX, value: \"ffffff\"}",
      Error: new Error()
    };
  });
});

/*  Not a pure module */
