// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as ColorFormat from "../../src/parsers/ColorFormat.res.mjs";

Vitest.describe("HEX format detection", () => {
  Vitest.test("detect standard HEX 6 chars", () => {
    let match = ColorFormat.getColorFormat("#ffffff");
    if (match !== undefined) {
      if (match === "HEX") {
        return;
      }
      throw {
        RE_EXN_ID: "Failure",
        _1: "Expected #ffffff to be HEX",
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: "Failure",
      _1: "Expected #ffffff to be HEX",
      Error: new Error()
    };
  });
  Vitest.test("detect standard HEX 3 chars", () => {
    let match = ColorFormat.getColorFormat("#fff");
    if (match !== undefined) {
      if (match === "HEX") {
        return;
      }
      throw {
        RE_EXN_ID: "Failure",
        _1: "Expected #fff to be HEX",
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: "Failure",
      _1: "Expected #fff to be HEX",
      Error: new Error()
    };
  });
  Vitest.test("detect HEX with alpha 4 and 8 chars", () => {
    let match = ColorFormat.getColorFormat("#f0f8");
    if (match !== undefined) {
      if (match === "HEX") {
        return;
      }
      throw {
        RE_EXN_ID: "Failure",
        _1: "Expected #f0f8 to be HEX",
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: "Failure",
      _1: "Expected #f0f8 to be HEX",
      Error: new Error()
    };
  });
  Vitest.test("detect full HEX with alpha", () => {
    let match = ColorFormat.getColorFormat("#12345678");
    if (match !== undefined) {
      if (match === "HEX") {
        return;
      }
      throw {
        RE_EXN_ID: "Failure",
        _1: "Expected #12345678 to be HEX",
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: "Failure",
      _1: "Expected #12345678 to be HEX",
      Error: new Error()
    };
  });
  Vitest.test("detect invalid HEX", () => {
    let match = ColorFormat.getColorFormat("ffffff");
    if (match === undefined) {
      return;
    }
    throw {
      RE_EXN_ID: "Failure",
      _1: "Expected ffffff to be None",
      Error: new Error()
    };
  });
});

/*  Not a pure module */
