// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HexToRgb$WcagColorContrast from "./transformers/HexToRgb.res.mjs";
import * as ColorFormat$WcagColorContrast from "./parsers/ColorFormat.res.mjs";
import * as ColorValues$WcagColorContrast from "./parsers/ColorValues.res.mjs";

let format = ColorFormat$WcagColorContrast.getColorFormat;

let values = ColorValues$WcagColorContrast.extract;

function rgb(s) {
  let fmt = ColorFormat$WcagColorContrast.getColorFormat(s);
  if (fmt === undefined) {
    return;
  }
  let match = ColorValues$WcagColorContrast.extract(s, fmt);
  if (match === undefined) {
    return;
  }
  if (match.format === "HEX") {
    return HexToRgb$WcagColorContrast.hexToRgb(match.value);
  }
  throw {
    RE_EXN_ID: "Match_failure",
    _1: [
      "WcagColorContrast.res",
      13,
      4
    ],
    Error: new Error()
  };
}

export {
  format,
  values,
  rgb,
}
/* ColorFormat-WcagColorContrast Not a pure module */
