// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ColorFormat$WcagColorContrast from "./parsers/ColorFormat.res.mjs";
import * as ColorValues$WcagColorContrast from "./parsers/ColorValues.res.mjs";

let format = ColorFormat$WcagColorContrast.getColorFormat;

let values = ColorValues$WcagColorContrast.extract;

export {
  format,
  values,
}
/* ColorFormat-WcagColorContrast Not a pure module */
