// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ColorFormat$WcagColorContrast from "./parsers/ColorFormat.res.mjs";

let format = ColorFormat$WcagColorContrast.getColorFormat;

export {
  format,
}
/* ColorFormat-WcagColorContrast Not a pure module */
