// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function hexToInt(hex) {
  return Stdlib_Int.fromString(hex, 16);
}

function hexToRgb(value) {
  let hex = value.startsWith("#") ? value.slice(1).trim() : value.trim();
  let len = hex.length;
  let normalized;
  if (len === 3) {
    let r = Stdlib_Option.getOr(hex[0], "0");
    let g = Stdlib_Option.getOr(hex[1], "0");
    let b = Stdlib_Option.getOr(hex[2], "0");
    normalized = r + r + g + g + b + b + "ff";
  } else if (len === 4) {
    let r$1 = Stdlib_Option.getOr(hex[0], "0");
    let g$1 = Stdlib_Option.getOr(hex[1], "0");
    let b$1 = Stdlib_Option.getOr(hex[2], "0");
    let a = Stdlib_Option.getOr(hex[3], "0");
    normalized = r$1 + r$1 + g$1 + g$1 + b$1 + b$1 + a + a;
  } else {
    normalized = len === 6 ? hex + "ff" : hex;
  }
  if (normalized.length !== 8) {
    return;
  }
  let r$2 = Stdlib_Option.getOr(Stdlib_Int.fromString(normalized.substring(0, 2), 16), 0);
  let g$2 = Stdlib_Option.getOr(Stdlib_Int.fromString(normalized.substring(2, 4), 16), 0);
  let b$2 = Stdlib_Option.getOr(Stdlib_Int.fromString(normalized.substring(4, 6), 16), 0);
  let aVal = Stdlib_Option.getOr(Stdlib_Int.fromString(normalized.substring(6, 8), 16), 0);
  let a$1 = aVal / 255.0;
  return {
    r: r$2,
    g: g$2,
    b: b$2,
    a: a$1
  };
}

export {
  hexToInt,
  hexToRgb,
}
/* No side effect */
